
export enum PartnerStatus {
    Active = "Active",
    Onboarding = "Onboarding",
    Inactive = "Inactive"
}

export interface Product {
    id: string; // uuid
    created_at: string;
    name: string;
    description: string;
    icon_url: string;
}

export interface Partner {
    id: string; // uuid
    created_at: string;
    product_id: string; // Foreign key to Product
    name: string;
    status: PartnerStatus;
    join_date: string; // ISO date string
    contact_person: {
        name: string;
        email: string;
    };
    description: string;
    logo_url: string;
}

// Type for creating a new partner. Omits fields generated by the system/DB.
export type NewPartner = Omit<Partner, 'id' | 'created_at' | 'product_id'>;

// Declare a global type for our configuration object
declare global {
  interface Window {
    APP_CONFIG: {
      SUPABASE_URL: string;
      SUPABASE_KEY: string;
      API_KEY: string;
    };
  }
}
